$(document).ready(function(){
    $("#development-image").click(function(){
      $("#development-image").toggle('1500').hide('1000');
      $("#development").show('1500');
    });
    $("#development").click(function(){
      $("#development").toggle('1500');
      $("#development-image").slideDown('1500');
    });
  });
  
  $(document).ready(function(){
    $("#design-image").click(function(){
      $("#design-image").toggle'1500').hide('1000');
      $("#design").show('1500');
    });
    $("#design").click(function(){
      $("#design").toggle('1500');
      $("#design-image").toggle('1500');
    });
  });
  
  $(document).ready(function(){
    $("#product-image").click(function(){
      $("#product-image").toggle('1500').hide('1000');
      $("#product").show('1500');
    });
    $("#product").click(function(){
      $("#product").slideUp('1500');
      $("#product-image").slideDown('1500');
    });
});
